---

- name: Assertions
  ansible.builtin.assert:
    that:
      - gpg_user_name is defined
      - gpg_pubkey is defined

- name: Set-up user
  ansible.builtin.include_tasks:
    file: setup-user.yml

- name: Copy public key file
  ansible.builtin.copy:
    src: "{{ gpg_pubkey }}"
    dest: "{{ gpg_home | default(gpg_home_default) }}/{{ gpg_pubkey }}"
    mode: "0644"
  become: yes
  become_user: "{{ gpg_user_name }}"

- name: Get key id from file
  ansible.builtin.shell: |
    set -o pipefail
    gpg --show-keys --with-colons {{ gpg_home | default(gpg_home_default) }}/{{ gpg_pubkey }} | \
    awk -F':' '$1=="pub" {print $5}'
  args:
    executable: /bin/bash
  changed_when: false
  become: yes
  become_user: "{{ gpg_user_name }}"
  register: __key_id
  environment:
    GNUPGHOME: "{{ gpg_home | default(gpg_home_default) }}"

- name: Get all GPG keys
  ansible.builtin.command: gpg --list-keys
  changed_when: false
  become: yes
  become_user: "{{ gpg_user_name }}"
  register: _gpg_keys
  environment:
    GNUPGHOME: "{{ gpg_home | default(gpg_home_default) }}"

- name: Import GPG public key
  ansible.builtin.command: gpg --import {{ gpg_home | default(gpg_home_default) }}/{{ gpg_pubkey }}
  become: yes
  become_user: "{{ gpg_user_name }}"
  changed_when: true
  when: __key_id.stdout not in _gpg_keys.stdout

- name: Set trust
  ansible.builtin.include_tasks:
    file: set-trust.yml
  vars:
    gpg_user_email: "{{ __key_id.stdout }}"
