---

- name: Load variables based on OS type
  ansible.builtin.include_tasks:
    file: vars.yml

- name: Install GPG
  ansible.builtin.include_tasks:
    file: install.yml

- name: Create/import GPG keys
  ansible.builtin.include_tasks:
    file: key.yml
  when: gpg_user_name is defined and gpg_user_name | length > 0
