---

- name: Load variables based on OS type
  ansible.builtin.include_tasks:
    file: vars.yml

- name: Install GPG
  ansible.builtin.include_tasks:
    file: install.yml
  when: gpg_install | bool

- name: Create keypair
  ansible.builtin.include_tasks:
    file: generate-keypair.yml
  when: gpg_generate_key | bool

- name: Import private key
  ansible.builtin.include_tasks:
    file: import-seckey.yml
  when: gpg_import_seckey | bool

- name: Import public key
  ansible.builtin.include_tasks:
    file: import-pubkey.yml
  when: gpg_import_pubkey | bool
